//
//  ExpectedMoveInteractorTests.swift
//  ExpectedMove
//
//  Created by Rene Laterveer on 6/8/16.
//  Copyright (c) 2016 Rene Laterveer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import ExpectedMove
import XCTest

class ExpectedMoveInteractorTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: ExpectedMoveInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupExpectedMoveInteractor()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupExpectedMoveInteractor()
    {
        sut = ExpectedMoveInteractor()
    }
    
    // MARK: Test doubles
    
    class ExpectedMoveInteractorOutputSpy: ExpectedMoveInteractorOutput
    {
        // MARK: Method call expectations
        var presentProfitLossDaysAheadCalled = false
        
        // MARK: Spied methods
        func presentProfitLossDaysAhead(response: ExpectedMove.FetchTicker.Response)
        {
            presentProfitLossDaysAheadCalled = true
        }
    }
    
    class FetchTickerWorkerSpy: FetchTickerWorker
    {
        // MARK: Method call expectations
        var fetchTickerCalled = false
        
        // MARK: Spied methods
        override func fetchTicker(ticker: String, completionHandler: (financeData: FinanceData) -> Void)
        {
            fetchTickerCalled = true
            financeDataService.fetchTicker(ticker, completionHandler: completionHandler)
        }
        
    }
    
    class CalculateExpectedMoveWorkerSpy: CalculateExpectedMoveWorker
    {
        // MARK: Method call expectations
        var calculateCalled = false

        // MARK: Spied methods
        override func calculate(price: Double, numberOfShares: Int, impliedVolatility: Double) -> [ProfitLoss] {
            calculateCalled = true
            return [ProfitLoss]()
        }
    }
    
    class FinanceDataMock: FinanceDataProtocol
    {
        func fetchTicker(ticker: String, completionHandler: (financeData: FinanceData) -> Void)
        {
            var financeData = FinanceData()
            financeData.lastTradePrice = 100.0
            completionHandler(financeData: financeData)
        }
    }
    
    // MARK: Tests
    
    func testFetchTickerShouldAskExpectedMoveWorkerToFetchTicker()
    {
        // Given
        let expectedMoveInteractorOutputSpy = ExpectedMoveInteractorOutputSpy()
        sut.output = expectedMoveInteractorOutputSpy
        let workerSpy = FetchTickerWorkerSpy(financeDataService: FinanceDataMock())
        sut.fetchTickerWorker = workerSpy
        var request = ExpectedMove.FetchTicker.Request()
        request.ticker = "AAPL"
        request.numberOfShares = "100"
        request.impliedVolatility = "0.182"
        
        // When
        sut.fetchTicker(request)
        
        // Then
        XCTAssert(workerSpy.fetchTickerCalled, "FetchTicker() should ask worker to fetch ticker data")
    }
    
    func testFetchTickerShouldAskCalculateExpectedMoveWorkerToCalculateExpectedMove()
    {
        // Given
        let expectedMoveInteractorOutputSpy = ExpectedMoveInteractorOutputSpy()
        sut.output = expectedMoveInteractorOutputSpy
        let fetchTickerWorkerSpy = FetchTickerWorkerSpy(financeDataService: FinanceDataMock())
        sut.fetchTickerWorker = fetchTickerWorkerSpy
        let calculateExpectedMoveWorkerSpy = CalculateExpectedMoveWorkerSpy()
        sut.calculateExpectedMoveWorker = calculateExpectedMoveWorkerSpy
        var request = ExpectedMove.FetchTicker.Request()
        request.ticker = "AAPL"
        request.numberOfShares = "100"
        request.impliedVolatility = "0.182"
        
        // When
        sut.fetchTicker(request)
        
        // Then
        XCTAssert(calculateExpectedMoveWorkerSpy.calculateCalled, "FetchTicker() should ask worker to calculate expected move")
    }
    
    func testFetchTickerShouldAskPresenterToFormatResult()
    {
        // Given
        let expectedMoveInteractorOutputSpy = ExpectedMoveInteractorOutputSpy()
        sut.output = expectedMoveInteractorOutputSpy
        let workerSpy = FetchTickerWorkerSpy(financeDataService: FinanceDataMock())
        sut.fetchTickerWorker = workerSpy
        var request = ExpectedMove.FetchTicker.Request()
        request.ticker = "AAPL"
        request.numberOfShares = "100"
        request.impliedVolatility = "0.182"
        
        // When
        sut.fetchTicker(request)
        
        // Then
        XCTAssert(expectedMoveInteractorOutputSpy.presentProfitLossDaysAheadCalled, "FetchTicker() should ask presenter to format expected move result")
    }
}
