//
//  FetchTickerWorker.swift
//  ExpectedMove
//
//  Created by Rene Laterveer on 6/9/16.
//  Copyright (c) 2016 Rene Laterveer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Fetch Ticker worker

class FetchTickerWorker
{
    var financeDataService: FinanceDataProtocol
    
    init(financeDataService: FinanceDataProtocol)
    {
        self.financeDataService = financeDataService
    }
    
    func fetchTicker(ticker: String, completionHandler: (financeData: FinanceData) -> Void)
    {
        financeDataService.fetchTicker(ticker) { (financeData) in
            completionHandler(financeData: financeData)
        }
    }
}

// MARK: - Finance Data API

protocol FinanceDataProtocol
{
    func fetchTicker(ticker: String, completionHandler: (financeData: FinanceData) -> Void)
}