//
//  StockAutoCompleteWorker.swift
//  ExpectedMove
//
//  Created by Rene on 28/06/16.
//  Copyright (c) 2016 Rene Laterveer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class StockAutoCompleteWorker
{
    // MARK: Business Logic
    
    var stockAutoCompleteService: StockAutoCompleteAPI
    
    init(stockAutoCompleteService: StockAutoCompleteAPI)
    {
        self.stockAutoCompleteService = stockAutoCompleteService
    }

    func stockAutoComplete(ticker: String, completionHandler: (stockAutoComplete: [StockAutoCompleteResult]) -> Void)
    {
        stockAutoCompleteService.stockAutoComplete(ticker) { (stockAutoComplete) in
            completionHandler(stockAutoComplete: stockAutoComplete)
        }
    }
}
