//
//  ExpectedMoveViewController.swift
//  ExpectedMove
//
//  Created by Rene Laterveer on 6/8/16.
//  Copyright (c) 2016 Rene Laterveer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ExpectedMoveViewControllerInput
{
    func displayProfitLossDaysAhead(viewModel: ExpectedMove.FetchTicker.ViewModel)
}

protocol ExpectedMoveViewControllerOutput
{
    func fetchTicker(request: ExpectedMove.FetchTicker.Request)
}

class ExpectedMoveViewController: UITableViewController, ExpectedMoveViewControllerInput
{
    var output: ExpectedMoveViewControllerOutput!
    var router: ExpectedMoveRouter!
    
    // MARK: Outlets
    
    @IBOutlet weak var tickerTextField: UITextField!
    
    
    // MARK: Object lifecycle
    
    override func awakeFromNib()
    {
        super.awakeFromNib()
        ExpectedMoveConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomethingOnLoad()
    }
    
    // MARK: Event handling
    
    func doSomethingOnLoad()
    {
        // NOTE: Ask the Interactor to do some work
    }
    
    // MARK: Display logic
    
    func displayProfitLossDaysAhead(viewModel: ExpectedMove.FetchTicker.ViewModel)
    {
        // NOTE: Display the result from the Presenter
        
        // nameTextField.text = viewModel.name
    }
}

extension ExpectedMoveViewController: UITextFieldDelegate
{
    func textFieldDidEndEditing(textField: UITextField) {
        let request = ExpectedMove.FetchTicker.Request(ticker: textField.text!)
        output.fetchTicker(request)
    }
}
