//
//  ExpectedMovePresenter.swift
//  ExpectedMove
//
//  Created by Rene Laterveer on 6/8/16.
//  Copyright (c) 2016 Rene Laterveer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ExpectedMovePresenterInput
{
    func presentProfitLossDaysAhead(response: ExpectedMove.FetchTicker.Response)
}

protocol ExpectedMovePresenterOutput: class
{
    func displayProfitLossDaysAhead(viewModel: ExpectedMove.FetchTicker.ViewModel)
}

class ExpectedMovePresenter: ExpectedMovePresenterInput
{
    weak var output: ExpectedMovePresenterOutput!
    
    // MARK: Presentation logic
    
    func presentProfitLossDaysAhead(response: ExpectedMove.FetchTicker.Response)
    {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        
        let viewModel = ExpectedMove.FetchTicker.ViewModel()
        output.displayProfitLossDaysAhead(viewModel)
    }
}
