//
//  ExpectedMoveInteractor.swift
//  ExpectedMove
//
//  Created by Rene Laterveer on 6/8/16.
//  Copyright (c) 2016 Rene Laterveer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ExpectedMoveInteractorInput
{
    func fetchTicker(request: ExpectedMove.FetchTicker.Request)
}

protocol ExpectedMoveInteractorOutput
{
    func presentProfitLossDaysAhead(response: ExpectedMove.FetchTicker.Response)
}

class ExpectedMoveInteractor: ExpectedMoveInteractorInput
{
    var output: ExpectedMoveInteractorOutput!
    var worker = FetchTickerWorker(financeDataService: FinanceDataAPI())
    
    // MARK: Business logic
    
    func fetchTicker(request: ExpectedMove.FetchTicker.Request)
    {
        let ticker = request.ticker
        
        // NOTE: Ask the Worker to do the work
        
        worker.fetchTicker(ticker) {
            expectedMoves in
            // NOTE: Pass the result to the Presenter
            
            let response = ExpectedMove.FetchTicker.Response()
            self.output.presentProfitLossDaysAhead(response)
        }
    }
}
