//
//  ExpectedMoveModels.swift
//  ExpectedMove
//
//  Created by Rene Laterveer on 6/8/16.
//  Copyright (c) 2016 Rene Laterveer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ExpectedMove {
    struct FetchTicker {
        struct Request {
            var ticker: String
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
