//
//  ExpectedMoveWorker.swift
//  ExpectedMove
//
//  Created by Rene Laterveer on 6/8/16.
//  Copyright (c) 2016 Rene Laterveer. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class ExpectedMoveWorker
{
    // MARK: Business Logic
    
    func fetchTicker(ticker: String, completionHandler: (expectedMoves: [ExpectedMove.FetchTicker.ProfitLoss]) -> Void)
    {
        // NOTE: Do the work
    }
}
